name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_PATH: 'MIDIFlux.sln'

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Debug --no-restore
    
    - name: Build verification
      run: |
        Write-Host "✅ Build completed successfully!" -ForegroundColor Green
        Write-Host "📝 Tests are run locally by developer before push" -ForegroundColor Yellow
      shell: pwsh

  build-check:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build Release configuration
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
    
    - name: Test publish (without artifacts)
      run: |
        Write-Host "Testing publish process..." -ForegroundColor Green
        dotnet publish src/MIDIFlux.App/MIDIFlux.App.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output ./test-publish `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=false `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          --verbosity minimal
        
        if (Test-Path "./test-publish/MIDIFlux.App.exe") {
          $size = (Get-Item "./test-publish/MIDIFlux.App.exe").Length / 1MB
          Write-Host "✅ Executable created successfully (${size:F1} MB)" -ForegroundColor Green
        } else {
          Write-Host "❌ Executable not found!" -ForegroundColor Red
          exit 1
        }
      shell: pwsh
